### ISSUE TITLE
forward OnCommandCalled(playerid, cmd[]);

### ISSUE THREAD

**Issue by YashasSamaga** [WillianLuigi/ICMD-8.0#1]
forward OnCommandCalled(playerid, cmd[]);

You forgot to add forward 
`OnCommandCalled(playerid, cmd[]);`

**Comment by WLSF** [comment]
Hi YashasSamaga, thank you for the feedback.

About your doubt, the forward is included inside icmd.inc, but to use this feature you've to add the callback flag on your gamemode.

See gm_icmd.pwn example, you'll found a line with:
#define ICMD_CALLBACK

I really appreciate your feedback, thanks again.

If you still have problems, contact me again.

**Comment by YashasSamaga** [comment]
Never noticed that :D 

Anyway instead of having a define why can't your include check if it is defined or not?

#if defined OnCommandCalled
//OnCommandCalled has been implemented 
#endif

What is this  ___@ICMD_GOTO_ADDR(label[])?
Are you trying to call the function?

**Comment by WLSF** [comment]
**__@ICMD_GOTO_ADDR** is used to call the command.
It breaks the current execution and redirect it to the cmd mark line.

_I'll take a look on your considerations, thanks at all._
